# Generated by Django 5.1.4 on 2025-03-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidlog',
            name='scanned_rfid',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='rfid_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
