# Generated by Django 5.1.4 on 2025-05-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancecorrection',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('halfday', 'Half Day'), ('overtime', 'Overtime'), ('absent', 'Absent')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('halfday', 'Halfday'), ('overtime', 'Overtime'), ('absent', 'Absent')], default='absent', max_length=10),
        ),
    ]
