# Generated by Django 5.1.4 on 2025-05-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendancecorrection_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present (On Time)'), ('late', 'Late (After Grace Period)'), ('halfday', 'Halfday (PM Arrival)'), ('overtime', 'Overtime (After End Time)'), ('absent', 'Absent (No Scan)')], default='absent', max_length=10),
        ),
    ]
