# Generated by Django 5.1.5 on 2025-05-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_auto_20250504_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancecorrection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
